export interface VisitDataResponse  {
  data: {
    master:  {
      master_id: string;
      f_type: string;
      master_type: string | null;
      session_count: number | null;
      owner_type: string;
      owner_id: string;
      c_owner_id: number;
      launch_source_group_id: number;
      launch_source_id: number;
      launch_source_type_id: number;
      sales_employee_id: string;
      cs_employee_id: string | null;
      customer_id: string;
      specialist_id: string | null;
      exams_service_id: string;
      exams_department_id: string;
      exams_doctor_id: string;
      appointment_note: string;
      appointment_affiliate_id: string | null;
      appointment_type: "exam" | "package" | "services";
      exams_reason: string | null;
      master_note: string;
      note_customer: string | null;
      expected_total: number;
      create_employee_id: string;
      update_employee_id: string | null;
      register_type_id: string;
      canceled_reason: string | null;
      with_relatives: boolean | null;
      endoscopic_service_type: string | null;
      endoscopic_cathartic: string | null;
      endoscopic_cathartic_used: string | null;
      endoscopic_cathartic_lasttime: string | null;
      appointment_order_number: number;
      order_discount_refcode: string | null;
      order_discount_value: number;
      register_delay_note: string | null;
      register_delay_date: string | null;
      package_id: string | null;
      is_register_delay: boolean | null;
      is_register_package: boolean;
      is_register_subclinical: boolean;
      is_exams: boolean;
      is_insurance: boolean | null;
      is_insurance_checkcard: boolean | null;
      is_insurance_approved: boolean | null;
      is_appointment: boolean;
      is_re_exams: boolean;
      is_paid: boolean | null;
      is_lab_first: boolean | null;
      customer_seft_fillinfo: boolean;
      customer_seft_checkin: boolean | null;
      appointment_date: string;
      register_date: string | null;
      create_date: string;
      erp_code: string;
      erp_type: string;
      employee_id: string | null;
      status: string;
    };
    visit:
    {
      master_id: string;
      f_type: string;
      master_type: string | null;
      session_count: number | null;
      owner_type: string;
      owner_id: string;
      c_owner_id: number;
      launch_source_group_id: number;
      launch_source_id: number;
      launch_source_type_id: number;
      sales_employee_id: string;
      cs_employee_id: string | null;
      customer_id: string;
      specialist_id: string | null;
      exams_service_id: string;
      exams_department_id: string;
      exams_doctor_id: string;
      appointment_note: string;
      appointment_affiliate_id: string | null;
      appointment_type: "exam" | "package" | "services";
      exams_reason: string | null;
      master_note: string;
      note_customer: string | null;
      expected_total: number;
      create_employee_id: string;
      update_employee_id: string | null;
      register_type_id: string;
      canceled_reason: string | null;
      with_relatives: boolean | null;
      endoscopic_service_type: string | null;
      endoscopic_cathartic: string | null;
      endoscopic_cathartic_used: string | null;
      endoscopic_cathartic_lasttime: string | null;
      appointment_order_number: number;
      order_discount_refcode: string | null;
      order_discount_value: number;
      register_delay_note: string | null;
      register_delay_date: string | null;
      package_id: string | null;
      is_register_delay: boolean | null;
      is_register_package: boolean;
      is_register_subclinical: boolean;
      is_exams: boolean;
      is_insurance: boolean | null;
      is_insurance_checkcard: boolean | null;
      is_insurance_approved: boolean | null;
      is_appointment: boolean;
      is_re_exams: boolean;
      is_paid: boolean | null;
      is_lab_first: boolean | null;
      customer_seft_fillinfo: boolean;
      customer_seft_checkin: boolean | null;
      appointment_date: string;
      register_date: string | null;
      create_date: string;
      erp_code: string;
      erp_type: string;
      employee_id: string | null;
      status: string;
    };
    package: any; // bạn có thể định nghĩa rõ nếu có structure
    owner: {
      customer_id: string;
      source_group: {
        id: number;
        name: string;
      };
      source: {
        id: number;
        name: string;
      };
      source_type: {
        id: number;
        name: string;
      };
      owner: any;
    };
    sales_employee: {
      id: string;
      name: string;
    };
    cs_employee: any;
    servicepoint: any;
    saleorders: any;
    prescriptionsheets: any;
  };
  message: string;
  status: boolean;
  client_ip: string;
}
